spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/znjhsit?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    ssl: false
    lettuce:
      pool:
        max-active: 8
        max-wait: 3000
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      # 本地Nacos地址
      server-addr: localhost:8848

#监控哪些端点，nacos图形界面都可以看到
management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露端口

mybatis:
  type-aliases-package: com.life.platform.common.model
  mapper-locations: classpath:mybatis/mapper/*.xml